### PR TITLE
Wrong calculation of overlapping events

### PR DESCRIPTION
**Pull request by dittodhole**
I have following events:

`var events = [
{
    'start': '2012-01-01 12:00:00',
    'end': '2012-01-01 13:00:00'
},
{
    'start': '2012-01-01 12:00:00',
    'end': '2012-01-01 12:00:00'
];`

The events do not get overlapped

### CODE REVIEW

**Comment by dittodhole** [comment]
i have enhanced my solution.
the cause:

if you have, eg

`var events = [
{
    'start': '2012-01-01 12:00:00',
    'end': '2012-01-01 12:00:00'
},
{
    'start': '2012-01-01 12:01:00',
    'end': '2012-01-01 12:01:00'
];`

the events still do not get overlapped.

i have switched the calculation-base to top/height instead of start/end - this is solution is more accurate!

**Comment by K-Phoen** [comment]
I need to take time to properly review this PR, and in the mean time I would like to start adding more tests to the current code base. I think that this kind of method should be tested, at least to prevent regressions.
Do you agree with that? Are you interested in adding tests for your PR? (of course, I can help you)

**Comment by santhureddy008** [comment]
@dittodhole : overlapEventsSeparate is ignored in changes file, no more needed here ?

**Comment by dittodhole** [comment]
@santhureddy008 uff ... nearly 4 years later ... i have no idea :neckbeard:

**Comment by santhureddy008** [comment]
@dittodhole : Thanks for response, I have adapted your overlapping events changes, but getting different issue(see below screenshot), so do I miss any other changes apart from below code, would you please suggest.

```
    totalEventsWidthPercentInOneColumn: 100,
```

_adjustOverlappingEvents: function ($weekDay) {
            var self = this;
            if (!self.options.allowCalEventOverlap) {
                return;
            }
            var partitions = self._groupOverlappingEventElements($weekDay);
            var widthOfPartition = self.options.totalEventsWidthPercentInOneColumn / partitions.length;
            jQuery.each(partitions, function (index, partition) {
                var left = widthOfPartition \* index;
                jQuery.each(partition, function (index, $event) {
                    $event.css({
                        width: widthOfPartition + '%',
                        left: left + '%',
                        right: 0
                    });
                });
            });
        },

```
    /*
      * Find groups of overlapping events
      */
    _groupOverlappingEventElements: function ($weekDay) {
        var $events = $weekDay.find('.wc-cal-event:visible');
        var complexEvents = jQuery.map($events, function (element, index) { 
            var $event = $(element);
            var position = $event.position();
            var height = $event.height();
            var calEvent = $event.data('calEvent');
            var complexEvent = { 
                'event': $event,
                'calEvent': calEvent,
                'top': position.top,
                'bottom': position.top + height
            };
            return complexEvent;
        }).sort(function (a, b) {
            var result = a.top - b.top;
            if (result) {
                return result;
            }
            return a.bottom - b.bottom;
        });
        var groups = [];
        jQuery.each(complexEvents, function (index, element) {
            var complexEvent = element;
            var $event = complexEvent.event;
            var group;
            jQuery.each(groups, function (index, element) {
                if (group) {
                    return;
                }

                if (complexEvent.bottom < element.top) {
                    group = element;
                    group.top = complexEvent.top;
                } else if (element.bottom < complexEvent.top) {
                    group = element;
                    group.bottom = complexEvent.bottom;
                }
            });
            if (!group) {
                group = {
                    'top': complexEvent.top,
                    'bottom': complexEvent.bottom,
                    'partition': []
                };
                groups.push(group);
            }/* else { // this is handled by line 1640ff
                group.top = Math.min(group.top, complexEvent.top);
                group.bottom = Math.max(group.bottom, complexEvent.bottom);
            }*/
            group.partition.push($event);
        });
        var partitions = [];
        jQuery.each(groups, function (index, element) {
            partitions.push(element.partition);
        });
        return partitions;
    },
```

calendar widget

**Comment by dittodhole** [comment]
@santhureddy008 it would be great, if you could provide a fiddle - so that I can debug this very issue directly ...

**Comment by dittodhole** [comment]
closing due to lack of interest.

**Pull request closed without merging**
