### PR TITLE
removed Date.parse(d) as it was returning a number instead of a date obje

### PR DESCRIPTION
**Pull request by deanoemcke**
removed Date.parse(d) as it was returning a number instead of a date object. this would fail later on when it attempts to call the getTime() method on it.

### CODE REVIEW

**Comment by deanoemcke** [comment]
this was happening when trying to create a freebusy with a start of "2011/10/14 14:00:00"

**Comment by K-Phoen** [comment]
Hi,

Thanks for your contribution. I know it's a bit late to ask this, but could you add unit tests for this PR? The tests are in the `test/tests.js` file, in the "date parsing" section.

**Comment by deanoemcke** [comment]
Hey,

It's been a long time since I have used the weekcalendar. From memory
my solution was not satisfactory and I reverted back to the original
code.
I tried writing a unit test for it just now but it seemed to pass
without any problems over the original code.
I'm certain at one point this code was giving me a lot of grief and if
the reply to my post is anything to go by, it appears at least one
other person was experiencing the same problems.
However, seeing as I am unable to produce a testable failure I would
recommend disregarding my contribution.
Cheers for the follow up.

Dean

On 27 April 2012 09:46, Kévin Gomez
reply@reply.github.com
wrote:

**Comment by K-Phoen** [comment]
I investigated a little and it appears that the date.js library replaces the Date.parse() method by its own parser. That's why the tests would not reproduce the issue.

As `Date.parse()` and `new Date()` both handle the same formats, your PR should have worked. I just need to find out why your solution wasn't satisfactory before applying a fix. I also need to find where exactly we need the date.js library to remove this dependency (IMO not so useful). But to do that, we need more unit tests in order to avoid regressions... this issue is bigger that it may seem :)

So until we find a good solution, I'll do as you said and close this PR. Thanks for your quick reply!

**Pull request closed without merging**
