### PR TITLE
more parameters for rendering calendar header

### PR DESCRIPTION
**Pull request by dittodhole**
currently i am in the need to render the weeknumber (which will is queryable by `$.datepicker.iso8601Week( date)` - see http://jqueryui.com/demos/datepicker/) to the header.
the current solution only provides a/one lousy parameter: `daysToShow`.

i've introduced `start` and `end` to do such calculations.

### CODE REVIEW

**Comment by K-Phoen** [comment]
I won't merge this PR as you both fix stuff and add new features/options. Can you separate the two issues and make different PR?

Besides, I don't think that the `_getCalendarTitle()` methods needs the `start` and `end`. If you want to access these values, you can do this:

``` js
var start = $('#calendar').weekCalendar('getCurrentFirstDay');
var end = $('#calendar').weekCalendar('getCurrentLastDay');
```

Concerning the "Wrong calculation of overlapping events" issue, I confirm the bug and will review your [commit](https://github.com/dittodhole/jquery-week-calendar/commit/567fccd17b1251a91df2d3e267b46cb9e2341362).

**Comment by dittodhole** [comment]
i've tried to separate the commits into different push requests - wasn't able to ... sry

i know, that i can get values from the outside, but i do not think, that going through the whole chain (creating a jquery-wrapper-object with `$('#calendar')` and calling the whole setup from the outside) is that _good_ option ...
maybe my solution isn't that good option either - what if someone needs more settings/values?
maybe handling some sort of "this-is-my-current-option/value"-set to the function would be way better ...

**Comment by K-Phoen** [comment]
> what if someone needs more settings/values?

Exactly.

> i know, that i can get values from the outside, but i do not think, that going through the whole chain (creating a jquery-wrapper-object with $('#calendar') and calling the whole setup from the outside) is that good option ...

So don't do it. You don't need to create a new jQuery object each time if you store the original object somewhere your callbacks can access it:

``` javascript
(function($, undefined) {
  var calendar = $('#calendar');

  var getWeekOfYear = function(date) {
    var onejan = new Date(date.getFullYear(), 0, 1);                                                                                                  
    return Math.ceil((((date - onejan) / 86400000) + onejan.getDay() + 1) / 7);
  };

  // on dom ready
  $(function() {
    calendar.weekCalendar({
      title: function() {
        var start = calendar.weekCalendar('getCurrentFirstDay');

        return 'Week ' + getWeekOfYear(start);
      }   
    }); 
  }); 
}(jQuery));
```

No extra processing, no dependency to the jquery ui datepicker. Does that fit your needs?

> maybe handling some sort of "this-is-my-current-option/value"-set to the function would be way better ...

This could be a solution, but I prefer mine. I think the (weekCalendar) user should take advantage of JavaScript scopes to keep a reference to the calendar.

**Comment by dittodhole** [comment]
actually closures came up to my mind either - but i've dumped the choice, as i try to avoid any overusage (due to internet explorer and its mem-leaks).
but this solution has a major downside: you need to create "get"-functions for each setting you'd like to access ...

the main-issue, i have with this approach, is the improper "way" in total ...
see ... actually you can get the options (more specific the `daysToShow`) with the closure-setup either - so why even handling this value to the external function-call?

now being restrictive and telling someone "hey, you could that with closures" (which, btw is a nice way), but internally still use the "bad" approach, isn't really a proper way of handling a codebase ...

so ... i believe that this issue has some deeper connection and claims some elevation of our understanding...

**Comment by dittodhole** [comment]
i will close this pull-request, as i will reset my whole fork ...

**Pull request closed without merging**
